// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"WolfPadMVZ","status":true,"description":"More robust gamepad status updates.","parameters":{"Analog as Digital":"true","Advanced Hold Tracking":"true","Advanced Keyboard Tracking":"false","Analog Threshold":"0.1"}}
];
